---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name: sigul-sign-docker
services:
  sigul-bridge:
    build:
      context: >-
        /Users/matt/Repositories/modeseven-lfreleng-actions/sigul-sign-docker
      dockerfile: Dockerfile.bridge
    command:
      - /usr/local/bin/sigul-init.sh
      - --role
      - bridge
      - --debug
      - --start-service
    container_name: sigul-bridge
    environment:
      DEBUG: "false"
      NSS_PASSWORD: auto_generated_ephemeral
      SIGUL_BRIDGE_CLIENT_PORT: "44334"
      SIGUL_BRIDGE_SERVER_PORT: "44333"
      SIGUL_ROLE: bridge
    hostname: sigul-bridge
    healthcheck:
      test:
        - CMD-SHELL
        - >-
          certutil -d sql:/var/sigul/nss/bridge -L -n sigul-ca >/dev/null 2>&1
          && certutil -d sql:/var/sigul/nss/bridge -L -n sigul-bridge-cert
          >/dev/null 2>&1
      timeout: 10s
      interval: 30s
      retries: 5
      start_period: 1m0s
    init: true
    networks:
      sigul-network: null
    ports:
      - mode: ingress
        target: 44334
        published: "44334"
        protocol: tcp
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    volumes:
      - type: volume
        source: sigul_bridge_data
        target: /var/sigul
        volume: {}
  sigul-server:
    build:
      context: >-
        /Users/matt/Repositories/modeseven-lfreleng-actions/sigul-sign-docker
      dockerfile: Dockerfile.server
    command:
      - /usr/local/bin/sigul-init.sh
      - --role
      - server
      - --debug
      - --start-service
    container_name: sigul-server
    depends_on:
      sigul-bridge:
        condition: service_healthy
        required: true
    environment:
      DEBUG: "false"
      NSS_PASSWORD: auto_generated_ephemeral
      SIGUL_ADMIN_PASSWORD: auto_generated_ephemeral
      SIGUL_ADMIN_USER: admin
      SIGUL_ROLE: server
    hostname: sigul-server
    init: true
    networks:
      sigul-network: null
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - type: volume
        source: sigul_server_data
        target: /var/sigul
        volume: {}
      - type: volume
        source: sigul_bridge_data
        target: /var/sigul/bridge-shared
        read_only: true
        volume: {}
networks:
  sigul-network:
    name: sigul-sign-docker_sigul-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
    labels:
      org.sigul.network.purpose: testing
      org.sigul.network.version: unified
    enable_ipv6: false
volumes:
  sigul_bridge_data:
    name: sigul-sign-docker_sigul_bridge_data
    driver: local
  sigul_server_data:
    name: sigul-sign-docker_sigul_server_data
    driver: local
